apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-migrate
  namespace: postgres9
spec:
  replicas: 1
  selector:
    matchLabels:
      name: konga-migrate
  template:
    metadata:
      labels:
        name: konga-migrate
    spec:
      containers:
        - name: postgres
          image: pantsel/konga
          imagePullPolicy: IfNotPresent
          resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "0.2"
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_PASSWORD
              value: "kong"
            - name: KONG_PG_HOST
              value: "engine-postgres.postgres9.svc.cluster.local"
            - name: KONG_PG_DATABASE
              value: "kong"
            - name: KONG_PG_PORT
              value: "5432"
          command: ["prepare"]
          args:
            [
              "-a",
              "postgres",
              "-u",
              "postgresql://konga:konga@engine-postgres.postgres9.svc.cluster.local:5432/konga_db",
            ]
