apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-migrate
  namespace: postgres9
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kong-migrate
  template:
    metadata:
      labels:
        name: kong-migrate
    spec:
      containers:
      - name: postgres
        image: kong:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_HOST
          value: "192.168.88.129"
        - name: KONG_PG_DATABASE
          value: "kong"
        - name: KONG_PG_PORT
          value: "30811"
        command: ["kong"]
        args: ["migrations", "bootstrap"]