apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-migrate
  namespace: postgres9-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kong-migrate
  template:
    metadata:
      labels:
        name: kong-migrate
    spec:
      containers:
      - name: postgres
        image: kong:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 2Gi
            cpu: "0.2"
          requests:
            memory: 1Gi
            cpu: "0.1" 
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_HOST
          value: "engine-postgres-svc.postgres9-dev.svc.cluster.local"
        - name: KONG_PG_DATABASE
          value: "kong"
        - name: KONG_PG_PORT
          value: "5432"
        command: ["kong"]
        args: ["migrations", "bootstrap"]