---
#kong.yml文件
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: apaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: registry.ds.digitwin.com.cn:5000/library/kong-forward:20230323001
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_HOST
          value: "postgres96-service.apaas.svc.cluster.local"
        - name: KONG_PG_DATABASE
          value: "kong_db_1"       
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_PORT
          value: "5432"                        
        - name: KONG_apaas_LISTEN       
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_apaas_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_apaas_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PLUGINS
          value: "bundled,forward"
        - name: KONG_PLUGINSERVER_NAMES
          value: "forward"
        - name: KONG_PLUGINSERVER_FORWARD_START_CMD
          value: "/usr/local/share/lua/5.1/kong/plugins/bin/forward"
        - name: KONG_PLUGINSERVER_FORWARD_QUERY_CMD
          value: "/usr/local/share/lua/5.1/kong/plugins/bin/forward -dump"
 
        ports:
        - containerPort: 8000
          protocol: TCP
          name: kong-proxy
        - containerPort: 8001
          protocol: TCP
          name: kong-apaas
        - containerPort: 8443
          protocol: TCP
          name: kong-proxy-ssl
        - containerPort: 8444
          protocol: TCP
          name: kong-apaas-ssl

---
apiVersion: v1
kind: Service
metadata:
  name: kong-svc-1
  namespace: apaas
  labels:
    app: kong-svc-1
spec:
  ports:
  - name: kong-port
    port: 8000
    protocol: TCP
    nodePort: 30819
  - name: kong-apaas-port
    port: 8001
    protocol: TCP
    nodePort: 30816
  selector:
    app: kong
  type: NodePort    
