---
#kong.yml文件
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: denengy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: registry.ds.digitwin.com.cn:5000/library/kong:2.8
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 4Gi
            cpu: "2"
          requests:
            memory: 2Gi
            cpu: "1"
        env:
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_HOST
          value: "postgres96-service.denengy.svc.cluster.local"
        - name: KONG_PG_DATABASE
          value: "kong"       
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_PG_PORT
          value: "5432"                        
        - name: KONG_ADMIN_LISTEN       
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PLUGINS
          value: bundled,forward
        - name: KONG_PLUGINSERVER_NAMES
          value: forward
        - name: KONG_PLUGINSERVER_FORWARD_START_CMD
          value: /usr/local/share/lua/5.1/kong/plugins/bin/forward
        - name: KONG_PLUGINSERVER_FORWARD_QUERY_CMD
          value: /usr/local/share/lua/5.1/kong/plugins/bin/forward -dump
        - name: KONG_DECLARATIVE_CONFIG
          value: /usr/local/share/lua/5.1/kong/plugins/cas/kong.yml
 
        ports:
        - containerPort: 8000
          protocol: TCP
          name: kong-proxy
        - containerPort: 8001
          hostPort: 8001
          protocol: TCP
          name: kong-admin
        - containerPort: 8443
          protocol: TCP
          name: kong-proxy-ssl
        - containerPort: 8444
          protocol: TCP
          name: kong-admin-ssl
        volumeMounts:
        - mountPath: /usr/local/share/lua/5.1/kong/plugins/cas
          name: kong-plugin
        - mountPath: /usr/local/share/lua/5.1/kong/plugins/bin
          name: kong-plugin-bin
        - mountPath: /etc/kong
          name: kong-conf 
      volumes:
      - name: kong-plugin
        persistentVolumeClaim:
          claimName: kong-plugin
      - name: kong-conf
        persistentVolumeClaim:
          claimName: kong-conf
      - name: kong-plugin-bin
        persistentVolumeClaim:
          claimName: kong-plugin-bin
---
apiVersion: v1
kind: Service
metadata:
  name: kong-svc
  namespace: denengy
  labels:
    app: kong-svc
spec:
  ports:
  - name: kong-port
    port: 8000
    protocol: TCP
    nodePort: 30829
  - name: kong-admin-port
    port: 8001
    protocol: TCP
    nodePort: 30826
  selector:
    app: kong
  type: NodePort    
