apiVersion: v1
kind: Namespace
metadata:
  name: kong-local-dev
  labels:
    name: kong-local-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres9-dev
  labels:
    name: postgres9-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-pv2-5g-dev
  labels:
    storage: sandbox-pv2-5g-dev
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pg-dev/pv2
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-pvc2-5g-dev
  namespace: postgres9-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sandbox-pv2-5g-dev

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-pv3-2g-dev
  labels:
    storage: sandbox-pv3-2g-dev
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pg-dev/pv3
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-pvc3-2g-dev
  namespace: kong-local-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sandbox-pv3-2g-dev

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-pv4-2g-dev
  labels:
    storage: sandbox-pv4-2g-dev
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pg-dev/pv4
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-pvc4-2g-dev
  namespace: kong-local-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sandbox-pv4-2g-dev

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-pv5-2g-dev
  labels:
    storage: sandbox-pv5-2g-dev
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/pg-dev/pv5
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sandbox-pvc5-2g-dev
  namespace: kong-local-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sandbox-pv5-2g-dev